version: '3.8'
services:

  authorization-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_JVM_ARGS_DEBUG=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8088
    ports:
      - "8080:8080"
      - "8088:8088"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=authorization
      - POSTGRES_USER=authorization
      - POSTGRES_PASSWORD=authorization
    ports:
      - 5432:5432
    volumes:
      - ./dev/postgresql:/var/lib/postgresql/data
      - ./dev/bootstrap/db/postgres:/docker-entrypoint-initdb.d